In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data = pd.read_csv("hypertension.csv")
data.head()

,C,Age,History,Patient,TakeMedication,Severity,BreathShortness,VisualChanges,NoseBleeding,Whendiagnoused,Systolic,Diastolic,ControlledDiet,Stages
0,Male,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
1,Female,18-34,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
2,Male,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
3,Female,35-50,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
4,Male,51-64,Yes,No,No,Mild,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)

In [3]:
data.shape

(1825, 14)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   C                1825 non-null   object
 1   Age              1825 non-null   object
 2   History          1825 non-null   object
 3   Patient          1825 non-null   object
 4   TakeMedication   1825 non-null   object
 5   Severity         1825 non-null   object
 6   BreathShortness  1825 non-null   object
 7   VisualChanges    1825 non-null   object
 8   NoseBleeding     1825 non-null   object
 9   Whendiagnoused   1825 non-null   object
 10  Systolic         1825 non-null   object
 11  Diastolic        1825 non-null   object
 12  ControlledDiet   1825 non-null   object
 13  Stages           1825 non-null   object
dtypes: object(14)
memory usage: 199.7+ KB

In [6]:
data.describe(include='all')

,C,Age,History,Patient,TakeMedication,Severity,BreathShortness,VisualChanges,NoseBleeding,Whendiagnoused,Systolic,Diastolic,ControlledDiet,Stages
count,1825,1825,1825,1825,1825,1825,1825,1825,1825,1825,1825,1825,1825,1825
unique,2,4,2,2,3,3,2,2,3,3,5,5,2,6
top,Female,51-64,Yes,No,No,Moderate,No,No,No,<1 Year,111 - 120,81 - 90,No,HYPERTENSION (Stage-1)
freq,913,475,1657,984,744,697,976,940,984,625,1008,708,984,648

In [7]:
data.isnull().sum()

C                  0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           0
Diastolic          0
ControlledDiet     0
Stages             0
dtype: int64

In [9]:
data.rename(columns={'C': 'Gender'}, inplace=True)

In [10]:
# Fix TakeMedication spacing issue
data['TakeMedication'].replace({'Yes ': 'Yes'}, inplace=True)

# Fix NoseBleeding spacing issue
data['NoseBleeding'].replace({'No ': 'No'}, inplace=True)

# Fix Systolic formatting
data['Systolic'].replace({'121-130': '121 - 130'}, inplace=True)
data['Systolic'].replace({'100+': '100 - 110'}, inplace=True)

# Fix Stage spelling issues
data['Stages'].replace({'HYPERTENSION (Stage-2).': 'HYPERTENSION (Stage-2)'}, inplace=True)
data['Stages'].replace({'HYPERTENSIVE CRISI': 'HYPERTENSIVE CRISIS'}, inplace=True)

# Check Diastolic incorrect values
print((data['Diastolic'] == '130+').sum())
print((data['Diastolic'] == '100+').sum())

# Correct Diastolic value
data['Diastolic'].replace({'130+': '100+'}, inplace=True)

4
237

C:\Users\Dell\AppData\Local\Temp\ipykernel_32244\2683066033.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['TakeMedication'].replace({'Yes ': 'Yes'}, inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_32244\2683066033.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['NoseBleeding'].replace({'No ': 'No'}, inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_32244\2683066033.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Systolic'].replace({'121-130': '121 - 130'}, inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_32244\2683066033.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Stages'].replace({'HYPERTENSION (Stage-2).': 'HYPERTENSION (Stage-2)'}, inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_32244\2683066033.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Diastolic'].replace({'130+': '100+'}, inplace=True)

In [11]:
# Fix TakeMedication
data['TakeMedication'] = data['TakeMedication'].replace({'Yes ': 'Yes'})

# Fix NoseBleeding
data['NoseBleeding'] = data['NoseBleeding'].replace({'No ': 'No'})

# Fix Systolic
data['Systolic'] = data['Systolic'].replace({
    '121-130': '121 - 130',
    '100+': '100 - 110'
})

# Fix Stages
data['Stages'] = data['Stages'].replace({
    'HYPERTENSION (Stage-2).': 'HYPERTENSION (Stage-2)',
    'HYPERTENSIVE CRISI': 'HYPERTENSIVE CRISIS'
})

# Check Diastolic values
print((data['Diastolic'] == '130+').sum())
print((data['Diastolic'] == '100+').sum())

# Fix Diastolic
data['Diastolic'] = data['Diastolic'].replace({'130+': '100+'})

0
241

In [13]:
data.drop_duplicates(inplace=True)

In [14]:
data.duplicated().sum()

np.int64(0)

In [16]:
data.to_csv("cleaned_hypertension.csv", index=False)

In [17]:
nominal_features = [
    'Gender', 'History', 'Patient', 'TakeMedication',
    'BreathShortness', 'VisualChanges',
    'NoseBleeding', 'ControlledDiet'
]

In [18]:
ordinal_features = [
    col for col in data.columns 
    if col not in nominal_features
]

ordinal_features.remove('Stages')

print(nominal_features)
print(ordinal_features)

['Gender', 'History', 'Patient', 'TakeMedication', 'BreathShortness', 'VisualChanges', 'NoseBleeding', 'ControlledDiet']
['Age', 'Severity', 'Whendiagnoused', 'Systolic', 'Diastolic']

In [19]:
for col in nominal_features:
    if set(data[col].unique()) == set(['Yes', 'No']):
        data[col] = data[col].map({'No': 0, 'Yes': 1})
    
    elif col == 'Gender':
        data[col] = data[col].map({'Male': 0, 'Female': 1})

In [20]:
data['Age'] = data['Age'].map({
    '18-34': 1,
    '35-50': 2,
    '51-64': 3,
    '65+': 4
})

In [21]:
data['Severity'] = data['Severity'].map({
    'Mild': 0,
    'Moderate': 1,
    'Sever': 2
})

In [22]:
data['Severity'] = data['Severity'].map({
    'Mild': 0,
    'Moderate': 1,
    'Sever': 2
})

In [24]:
data['Whendiagnoused'] = data['Whendiagnoused'].map({
    '<1 Year': 1,
    '1 - 5 Years': 2,
    '>5 Years': 3
})

In [25]:
data['Systolic'] = data['Systolic'].map({
    '100 - 110': 0,
    '111 - 120': 1,
    '121 - 130': 2,
    '130+': 3
})

In [26]:
data['Diastolic'] = data['Diastolic'].map({
    '70 - 80': 0,
    '81 - 90': 1,
    '91 - 100': 2,
    '100+': 3
})

In [29]:
data['Stages'] = data['Stages'].map({
    'NORMAL': 0,
    'HYPERTENSION (Stage-1)': 1,
    'HYPERTENSION (Stage-2)': 2,
    'HYPERTENSIVE CRISIS': 3
})

In [30]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

data[ordinal_features] = scaler.fit_transform(data[ordinal_features])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py:776: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmin(X, axis=axis))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py:793: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmax(X, axis=axis))

In [31]:
print(data.isnull().sum())

Gender                0
Age                   0
History               0
Patient               0
TakeMedication        0
Severity           1348
BreathShortness       0
VisualChanges         0
NoseBleeding          0
Whendiagnoused        0
Systolic            324
Diastolic             0
ControlledDiet        0
Stages             1348
dtype: int64

In [33]:
print("Severity:", data['Severity'].unique())
print("Systolic:", data['Systolic'].unique())
print("Stages:", data['Stages'].unique())

Severity: [nan]
Systolic: [0.33333333        nan 1.         0.         0.66666667]
Stages: [nan]

In [34]:
# Remove leading/trailing spaces from all string columns
data = data.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Convert everything to consistent format
data['Severity'] = data['Severity'].str.title()
data['Stages'] = data['Stages'].str.upper()

AttributeError: Can only use .str accessor with string values!

In [35]:
data = pd.read_csv("hypertension.csv")

In [36]:
# Strip spaces from all object columns
data = data.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [37]:
print("Severity:", data['Severity'].unique())
print("Systolic:", data['Systolic'].unique())
print("Stages:", data['Stages'].unique())

Severity: ['Mild' 'Sever' 'Moderate']
Systolic: ['111 - 120' '121- 130' '130+' '100+' '121 - 130']
Stages: ['HYPERTENSION (Stage-1)' 'HYPERTENSION (Stage-2)' 'HYPERTENSIVE CRISIS'
 'HYPERTENSION (Stage-2).' 'HYPERTENSIVE CRISI' 'NORMAL']

In [38]:
data['Severity'] = data['Severity'].map({
    'Mild': 0,
    'Moderate': 1,
    'Sever': 2
})

In [39]:
print(data['Severity'].isnull().sum())

0

In [40]:
print(data['Systolic'].unique())
print(data['Stages'].unique())

['111 - 120' '121- 130' '130+' '100+' '121 - 130']
['HYPERTENSION (Stage-1)' 'HYPERTENSION (Stage-2)' 'HYPERTENSIVE CRISIS'
 'HYPERTENSION (Stage-2).' 'HYPERTENSIVE CRISI' 'NORMAL']

In [41]:
print(data['Systolic'].unique())

['111 - 120' '121- 130' '130+' '100+' '121 - 130']

In [42]:
data['Systolic'] = data['Systolic'].replace({
    '121- 130': '121 - 130'
})

In [43]:
data['Systolic'] = data['Systolic'].map({
    '100+': 0,
    '111 - 120': 1,
    '121 - 130': 2,
    '130+': 3
})

In [44]:
print(data['Systolic'].isnull().sum())

0

In [45]:
print(data['Diastolic'].unique())

['81 - 90' '91 - 100' '100+' '130+' '70 - 80']

In [46]:
import pandas as pd

data = pd.read_csv("hypertension.csv")

In [47]:
data = data.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [48]:
binary_cols = [
    'History', 'Patient', 'TakeMedication',
    'BreathShortness', 'VisualChanges',
    'NoseBleeding', 'ControlledDiet'
]

for col in binary_cols:
    data[col] = data[col].map({'No': 0, 'Yes': 1})

In [50]:
import pandas as pd
data = pd.read_csv("hypertension.csv")

In [51]:
data = data.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [52]:
nominal_features = [
    'Gender', 'History', 'Patient', 'TakeMedication',
    'BreathShortness', 'VisualChanges',
    'NoseBleeding', 'ControlledDiet'
]

ordinal_features = [
    col for col in data.columns if col not in nominal_features
]

ordinal_features.remove('Stages')

print(nominal_features)
print(ordinal_features)

['Gender', 'History', 'Patient', 'TakeMedication', 'BreathShortness', 'VisualChanges', 'NoseBleeding', 'ControlledDiet']
['C', 'Age', 'Severity', 'Whendiagnoused', 'Systolic', 'Diastolic']

In [54]:
data.rename(columns={'C': 'Gender'}, inplace=True)

In [55]:
for col in nominal_features:
    if set(data[col].unique()) == set(['Yes', 'No']):
        data[col] = data[col].map({'No': 0, 'Yes': 1})
    
    elif col == 'Gender':
        data[col] = data[col].map({'Male': 0, 'Female': 1})

In [56]:

data['Age'] = data['Age'].map({
    '18-34': 1,
    '35-50': 2,
    '51-64': 3,
    '65+': 4
})

In [57]:
data['Severity'] = data['Severity'].map({
    'Mild': 0,
    'Moderate': 1,
    'Sever': 2
})

In [59]:
data['Whendiagnoused'] = data['Whendiagnoused'].map({
    '<1 Year': 1,
    '1 - 5 Years': 2,
    '>5 Years': 3
})

In [60]:
print(data['Whendiagnoused'].isnull().sum())

0

In [61]:
data['Systolic'] = data['Systolic'].replace({
    '121- 130': '121 - 130'
})

In [ ]:
data['Systolic'] = data['Systolic'].map({
    '100+': 0,
    '111 - 120': 1,
    '121 - 130': 2,
    '130+': 3
})

In [62]:
data['Systolic'] = data['Systolic'].map({'100 - 110': 0, '111 - 120': 1, '121 - 130': 2, '130+': 3})
data['Diastolic'] = data['Diastolic'].map({'70 - 80': 0, '81 - 90': 1, '91 - 100': 2, '100+': 3})

In [63]:
data['Stages'] = data['Stages'].map({
    'NORMAL': 0,
    'HYPERTENSION (Stage-1)': 1,
    'HYPERTENSION (Stage-2)': 2,
    'HYPERTENSIVE CRISIS': 3
})

In [64]:
print(data.isnull().sum())

Gender             0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           4
Diastolic          4
ControlledDiet     0
Stages             2
dtype: int64

In [65]:
print("Unmatched Systolic:")
print(data.loc[data['Systolic'].isnull(), 'Systolic'])

print("Unmatched Diastolic:")
print(data.loc[data['Diastolic'].isnull(), 'Diastolic'])

print("Unmatched Stages:")
print(data.loc[data['Stages'].isnull(), 'Stages'])

Unmatched Systolic:
142   NaN
187   NaN
696   NaN
697   NaN
Name: Systolic, dtype: float64
Unmatched Diastolic:
142   NaN
187   NaN
696   NaN
697   NaN
Name: Diastolic, dtype: float64
Unmatched Stages:
142   NaN
257   NaN
Name: Stages, dtype: float64

In [66]:
print(data['Systolic'].unique())
print(data['Diastolic'].unique())
print(data['Stages'].unique())

[ 1.  2.  3. nan]
[ 1.  2.  3. nan  0.]
[ 1.  2.  3. nan  0.]

In [69]:
data['Systolic'] = data['Systolic'].fillna(0)

In [70]:
data['Diastolic'] = data['Diastolic'].fillna(0)

In [71]:
data['Stages'] = data['Stages'].fillna(data['Stages'].mode()[0])

In [72]:
print(data.isnull().sum())

Gender             0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           0
Diastolic          0
ControlledDiet     0
Stages             0
dtype: int64

In [74]:
print(data.isnull().sum())

Gender             0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           0
Diastolic          0
ControlledDiet     0
Stages             0
dtype: int64

In [75]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data[ordinal_features] = scaler.fit_transform(data[ordinal_features])

In [76]:
print(data.head())

   Gender       Age  History  Patient  TakeMedication  Severity  \
0       0  0.000000        1        0               0       0.0
1       1  0.000000        1        0               0       0.0
2       0  0.333333        1        0               0       0.0
3       1  0.333333        1        0               0       0.0
4       0  0.666667        1        0               0       0.0

   BreathShortness  VisualChanges  NoseBleeding  Whendiagnoused  Systolic  \
0                0              0             0             0.0  0.333333
1                0              0             0             0.0  0.333333
2                0              0             0             0.0  0.333333
3                0              0             0             0.0  0.333333
4                0              0             0             0.0  0.333333

   Diastolic  ControlledDiet  Stages
0   0.333333               0     1.0
1   0.333333               0     1.0
2   0.333333               0     1.0
3   0.333333               0     1.0
4   0.333333               0     1.0

In [77]:
data.to_csv("encoded_hypertension.csv", index=False)